import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto, Lora, Source_Sans_3 } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: "300",
});

const lora = Lora({ subsets: ["latin"] });
const sora = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NEAR Founder Co-Pilot",
  description: "Generated by NEAR Horizon",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/*  Regarding the font contrast against the background `inter` with default weight looks better than  `roboto` */}
      <body className={`${inter.className} dark`}>{children}</body>
    </html>
  );
}
