import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto, Lora, Source_Sans_3 } from "next/font/google";
import { Providers } from "./providers";
import { ironSessionConfig } from "@/auth/iron-session";
import { User } from "@/auth/user";
import { getIronSession } from "iron-session";
import { cookies } from "next/headers";
import "@near-wallet-selector/modal-ui/styles.css";
import { Wallet } from '../components/near-wallet';

const wallet = new Wallet({ createAccessKeyFor: "social.near" })

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: "300",
});

const lora = Lora({ subsets: ["latin"] });
const sora = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NEAR Founder Co-Pilot",
  description: "Generated by NEAR Horizon",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { save, destroy, ...user } = await getIronSession<User>(cookies(), ironSessionConfig);

  return (
    <html lang="en">
      <Providers user={user} />
      {/*  Regarding the font contrast against the background `inter` with default weight looks better than  `roboto` */}
      <body className={`${inter.className} dark`}>{children}</body>
    </html>
  );
}
